/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 3"
  https://create.arduino.cc/cloud/things/af9039a3-d087-4155-aeaf-857da7e67e16 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudColor rGB;
  int blink_speed;
  bool blink_switch;
  bool loop_switch;
  bool relay_1;
  bool relay_2;
  bool switch_rgb;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier carrier;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  while (ArduinoCloud.connected() != 1) {
    ArduinoCloud.update();
    delay(500);
  }
  
  delay(500);
  CARRIER_CASE = false;
  carrier.begin();
  carrier.display.setRotation(0);
}

void loop() {
  uint8_t r,g,b;
  ArduinoCloud.update();
  // Your code here 
  rGB.getValue().getRGB(r, g, b);
  if (switch_rgb == true) {
    lightsOn();
  } else {
    lightsOff();
  }
  
  if (loop_switch == true) {
    for (int ring = 0; ring<=4; ring++) {
      carrier.leds.setPixelColor(ring, g, r, b);
      carrier.leds.show();
      delay(100);
      carrier.leds.clear();
    }
  } else {
    lightsOff();
  }
  
  if (blink_switch == true) {
    lightsOn();
    delay(blink_speed);
    lightsOff();
    delay(blink_speed);
  }
  
  if (relay_1 == true) {
    carrier.Relay1.open();
  } else {
    carrier.Relay1.close();
  }
  
  if (relay_2 == true) {
    carrier.Relay2.open();
  } else {
    carrier.Relay2.close();
  }
  
  delay(100);
}

void lightsOn() {
  uint8_t r,g,b;
  rGB.getValue().getRGB(r,g,b);
  carrier.leds.setPixelColor(0, g,r,b);
  carrier.leds.setPixelColor(1, g,r,b);
  carrier.leds.setPixelColor(2, g,r,b);
  carrier.leds.setPixelColor(3, g,r,b);
  carrier.leds.setPixelColor(4, g,r,b);
  carrier.leds.show();
}

void lightsOff() {
  carrier.leds.setPixelColor(0, 0,0,0);
  carrier.leds.setPixelColor(1, 0,0,0);
  carrier.leds.setPixelColor(2, 0,0,0);
  carrier.leds.setPixelColor(3, 0,0,0);
  carrier.leds.setPixelColor(04, 0,0,0);
  carrier.leds.show();
}

/*
  Since BlinkSpeed is READ_WRITE variable, onBlinkSpeedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBlinkSpeedChange()  {
}
/*
  Since RGB is READ_WRITE variable, onRGBChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRGBChange()  {
}
/*
  Since BlinkSwitch is READ_WRITE variable, onBlinkSwitchChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBlinkSwitchChange()  {
}
/*
  Since LoopSwitch is READ_WRITE variable, onLoopSwitchChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLoopSwitchChange()  {
}
/*
  Since Relay1 is READ_WRITE variable, onRelay1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay1Change()  {
}
/*
  Since Relay2 is READ_WRITE variable, onRelay2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay2Change()  {
}
/*
  Since SwitchRgb is READ_WRITE variable, onSwitchRgbChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitchRgbChange()  {
}
